enum class TokenType {
    LEFT_PAREN,
    RIGHT_PAREN,
    LEFT_BRACE,
    RIGHT_BRACE,
    COMMA,
    DOT,
    MINUS,
    PLUS,
    SLASH,
    STAR,
    COLON,

    BANG,
    BANG_EQ,
    EQ,
    EQ_EQ,
    GREATER,
    GREATER_EQ,
    LESS,
    LESS_EQ,

    IDENTIFIER, STRING, NUMBER,

    AND, ELSE, FALSE, STRUCT, ENUM, WHERE, OVER, FOR, WHILE, LOOP,
    OR, IF, RETURN, BREAK, CONTINUE, TRUE, LET, PRINT, WITH, DO, END,
    THEN, IN,

    EOF,
}
