enum class TokenType {
    LEFT_PAREN, RIGHT_PAREN,
    LEFT_BRACE, RIGHT_BRACE,
    COMMA,
    DOT,
    MINUS, PLUS,
    SLASH, STAR,
    COLON,
    PERCENT,

    EQ,
    IS,
    ISNT,
    NOT,
    GREATER,
    GREATER_EQ,
    LESS,
    LESS_EQ,

    PIPE, AMPERSAND,

    IDENTIFIER, STRING, NUMBER,

    AND, ELSE, FALSE, STRUCT, ENUM, WHERE, OVER, FOR, WHILE, LOOP,
    OR, IF, RETURN, BREAK, CONTINUE, TRUE, LET, PRINT, WITH, DO, END,
    THEN, IN,

    EOF,
}
